// keylist.inc
//
// Keyboard scankey identification





char x0100_a_escape[]=   "alt_escape;";
char x011b_c_escape[]=   "ctrl_escape;";
char x011b_escape[]=     "escape;";
char x011b_s_escape[]=   "shift_escape;";
char x0300_c_2[]=        "ctrl_2;";
char x071e_c_6[]=        "ctrl_6;";
char x0c1f_c_hyphen[]=   "ctrl_hyphen;";
char x0e08_backspace[]=  "backspace;";
char x0f00_s_tab[]=      "shift_tab;";
char x0f09_tab[]=        "tab;";
char x1000_a_q[]=        "alt_q;";
char x1011_c_q[]=        "ctrl_q;";
char x1100_a_w[]=        "alt_w;";
char x1117_c_w[]=        "ctrl_w;";
char x1200_a_e[]=        "alt_e;";
char x1205_c_e[]=        "ctrl_e;";
char x1300_a_r[]=        "alt_r;";
char x1312_c_r[]=        "ctrl_r;";
char x1400_a_t[]=        "alt_t;";
char x1414_c_t[]=        "ctrl_t;";
char x1500_a_y[]=        "alt_y;";
char x1519_c_y[]=        "ctrl_y;";
char x1600_a_u[]=        "alt_u;";
char x1615_c_u[]=        "ctrl_u;";
char x1700_a_i[]=        "alt_i;";
char x1709_c_i[]=        "ctrl_i;";
char x1800_a_o[]=        "alt_o;";
char x180f_c_o[]=        "ctrl_o;";
char x1900_a_p[]=        "alt_p;";
char x1910_c_p[]=        "ctrl_p;";
char x1c0a_c_enter[]=    "ctrl_enter;";
char x1c0d_enter[]=      "enter;";
char x1e00_a_a[]=        "alt_a;";
char x1e00_c_a[]=        "ctrl_a;";
char x1f00_a_s[]=        "alt_s;";
char x1f13_c_s[]=        "ctrl_s;";
char x2000_a_d[]=        "alt_d;";
char x2004_c_d[]=        "ctrl_d;";
char x2100_a_f[]=        "alt_f;";
char x2106_c_f[]=        "ctrl_f;";
char x2200_a_g[]=        "alt_g;";
char x2207_c_g[]=        "ctrl_g;";
char x2300_a_h[]=        "alt_h;";
char x2308_c_h[]=        "ctrl_h;";
char x2400_a_j[]=        "alt_j;";
char x240a_c_j[]=        "ctrl_j;";
char x2500_a_k[]=        "alt_k;";
char x250b_c_k[]=        "ctrl_k;";
char x2600_a_l[]=        "alt_l;";
char x260c_c_l[]=        "ctrl_l;";
char x2900_a_tilda[]=    "alt_tilda;";
char x2b00_a_backslash[]="alt_backslash;";
char x2b1c_c_backslash[]="ctrl_backslash;";
char x2c00_a_z[]=        "alt_z;";
char x2c1a_c_z[]=        "ctrl_z;";
char x2d00_a_x[]=        "alt_x;";
char x2d18_c_x[]=        "ctrl_x;";
char x2e00_a_c[]=        "alt_c;";
char x2e03_c_c[]=        "ctrl_c;";
char x2f00_a_v[]=        "alt_v;";
char x2f16_c_v[]=        "ctrl_v;";
char x3000_a_b[]=        "alt_b;";
char x3002_c_b[]=        "ctrl_b;";
char x3100_a_n[]=        "alt_n;";
char x310e_c_n[]=        "ctrl_n;";
char x3200_a_m[]=        "alt_m;";
char x320d_c_m[]=        "ctrl_m;";
char x3300_a_comma[]=    "alt_comma;";
char x3400_a_period[]=   "alt_period;";
char x3500_a_slash[]=    "alt_slash;";
char x3b00_f1[]=         "f1;";
char x3c00_f2[]=         "f2;";
char x3d00_f3[]=         "f3;";
char x3e00_f4[]=         "f4;";
char x3f00_f5[]=         "f5;";
char x4000_f6[]=         "f6;";
char x4100_f7[]=         "f7;";
char x4200_f8[]=         "f8;";
char x4300_f9[]=         "f9;";
char x4400_f10[]=        "f10;";
char x4700_home[]=       "home;";
char x47e0_g_home[]=     "grey_home;";
char x47e0_s_g_home[]=   "shift_grey_home;";
char x4800_up[]=         "up;";
char x48e0_g_up[]=       "grey_up;";
char x48e0_s_g_up[]=     "shift_grey_up;";
char x4900_pgup[]=       "pgup;";
char x49e0_g_pgup[]=     "grey_pgup;";
char x49e0_s_g_pgup[]=   "shift_grey_pgup;";
char x4b00_left[]=       "left;";
char x4be0_g_left[]=     "grey_left;";
char x4be0_s_g_left[]=   "shift_grey_left;";
char x4c00_center[]=     "center;";
char x4d00_right[]=      "right;";
char x4de0_g_right[]=    "grey_right;";
char x4de0_s_g_right[]=  "shift_grey_right;";
char x4f00_end[]=        "end;";
char x4fe0_g_end[]=      "grey_end;";
char x4fe0_s_g_end[]=    "shift_grey_end;";
char x5000_down[]=       "down;";
char x50e0_g_down[]=     "grey_down;";
char x50e0_s_g_down[]=   "shift_grey_down;";
char x5100_pgdn[]=       "pgdn;";
char x51e0_g_pgdn[]=     "grey_pgdn;";
char x51e0_s_g_pgdn[]=   "shift_grey_pgdn;";
char x5200_insert[]=     "insert;";
char x52e0_g_insert[]=   "grey_insert;";
char x52e0_s_g_insert[]= "shift_grey_insert;";
char x5300_delete[]=     "delete;";
char x53e0_g_delete[]=   "grey_delete;";
char x53e0_s_g_delete[]= "shift_grey_delete;";
char x5400_s_f1[]=       "shift_f1;";
char x5500_s_f2[]=       "shift_f2;";
char x5600_s_f3[]=       "shift_f3;";
char x5700_s_f4[]=       "shift_f4;";
char x5800_s_f5[]=       "shift_f5;";
char x5900_s_f6[]=       "shift_f6;";
char x5a00_s_f7[]=       "shift_f7;";
char x5b00_s_f8[]=       "shift_f8;";
char x5c00_s_f9[]=       "shift_f9;";
char x5d00_s_f10[]=      "shift_f10;";
char x5e00_c_f1[]=       "ctrl_f1;";
char x5f00_c_f2[]=       "ctrl_f2;";
char x6000_c_f3[]=       "ctrl_f3;";
char x6100_c_f4[]=       "ctrl_f4;";
char x6200_c_f5[]=       "ctrl_f5;";
char x6300_c_f6[]=       "ctrl_f6;";
char x6400_c_f7[]=       "ctrl_f7;";
char x6500_c_f8[]=       "ctrl_f8;";
char x6600_c_f9[]=       "ctrl_f9;";
char x6700_c_f10[]=      "ctrl_f10;";
char x6800_a_f1[]=       "alt_f1;";
char x6900_a_f2[]=       "alt_f2;";
char x6a00_a_f3[]=       "alt_f3;";
char x6b00_a_f4[]=       "alt_f4;";
char x6c00_a_f5[]=       "alt_f5;";
char x6d00_a_f6[]=       "alt_f6;";
char x6e00_a_f7[]=       "alt_f7;";
char x6f00_a_f8[]=       "alt_f8;";
char x7000_a_f9[]=       "alt_f9;";
char x7100_a_f10[]=      "alt_f10;";
char x7300_c_left[]=     "ctrl_left;";
char x73e0_c_g_left[]=   "ctrl_grey_left;";
char x7400_c_right[]=    "ctrl_right;";
char x74e0_c_g_right[]=  "ctrl_grey_right;";
char x7500_c_end[]=      "ctrl_end;";
char x75e0_c_g_end[]=    "ctrl_grey_end;";
char x7600_c_pgdn[]=     "ctrl_pgdn;";
char x76e0_c_g_pgdn[]=   "ctrl_grey_pgdn;";
char x7700_c_home[]=     "ctrl_home;";
char x77e0_c_g_home[]=   "ctrl_grey_home;";
char x7800_a_1[]=        "alt_1;";
char x7900_a_2[]=        "alt_2;";
char x7a00_a_3[]=        "alt_3;";
char x7b00_a_4[]=        "alt_4;";
char x7c00_a_5[]=        "alt_5;";
char x7d00_a_6[]=        "alt_6;";
char x7e00_a_7[]=        "alt_7;";
char x7f00_a_8[]=        "alt_8;";
char x8000_a_9[]=        "alt_9;";
char x8100_a_0[]=        "alt_0;";
char x8200_a_hyphen[]=   "alt_hyphen;";
char x8300_a_equal[]=    "alt_equal;";
char x8400_c_pgup[]=     "ctrl_pgup;";
char x84e0_c_g_pgup[]=   "ctrl_grey_pgup;";
char x8500_f11[]=        "f11;";
char x8600_f12[]=        "f12;";
char x8700_s_f11[]=      "shift_f11;";
char x8800_s_f12[]=      "shift_f12;";
char x8900_c_f11[]=      "ctrl_f11;";
char x8a00_c_f12[]=      "ctrl_f12;";
char x8b00_a_f11[]=      "alt_f11;";
char x8c00_a_f12[]=      "alt_f12;";
char x8d00_c_up[]=       "ctrl_up;";
char x8de0_c_g_up[]=     "ctrl_grey_up;";
char x8f00_c_center[]=   "ctrl_center;";
char x9100_c_down[]=     "ctrl_down;";
char x91e0_c_g_down[]=   "ctrl_grey_down;";
char x9200_c_insert[]=   "ctrl_insert;";
char x92e0_c_g_insert[]= "ctrl_grey_insert;";
char x9300_c_delete[]=   "ctrl_delete;";
char x93e0_c_g_delete[]= "ctrl_grey_delete;";
char x9400_c_tab[]=      "ctrl_tab;";
char x9700_a_g_home[]=   "alt_grey_home;";
char x9800_a_g_up[]=     "alt_grey_up;";
char x9900_a_g_pgup[]=   "alt_grey_pgup;";
char x9b00_a_g_left[]=   "alt_grey_left;";
char x9d00_a_g_right[]=  "alt_grey_right;";
char x9f00_a_g_end[]=    "alt_grey_end;";
char xa000_a_g_down[]=   "alt_grey_down;";
char xa100_a_g_pgdn[]=   "alt_grey_pgdn;";
char xa200_a_g_insert[]= "alt_grey_insert;";
char xa300_a_g_delete[]= "alt_grey_delete;";
char xa500_a_tab[]=      "alt_tab;";
char xa600_a_g_enter[]=  "alt_grey_enter;";
char xe00a_c_g_enter[]=  "ctrl_grey_enter;";
char xe00d_g_enter[]=    "grey_enter;";
char xe00d_s_g_enter[]=  "shift_grey_enter;";




ushort key_listing[] = {
    0x0100, (ushort)(&x0100_a_escape),
    0x011b, (ushort)(&x011b_c_escape),
    0x011b, (ushort)(&x011b_escape),
    0x011b, (ushort)(&x011b_s_escape),
    0x0300, (ushort)(&x0300_c_2),
    0x071e, (ushort)(&x071e_c_6),
    0x0c1f, (ushort)(&x0c1f_c_hyphen),
    0x0e08, (ushort)(&x0e08_backspace),
    0x0f00, (ushort)(&x0f00_s_tab),
    0x0f09, (ushort)(&x0f09_tab),
    0x1000, (ushort)(&x1000_a_q),
    0x1011, (ushort)(&x1011_c_q),
    0x1100, (ushort)(&x1100_a_w),
    0x1117, (ushort)(&x1117_c_w),
    0x1200, (ushort)(&x1200_a_e),
    0x1205, (ushort)(&x1205_c_e),
    0x1300, (ushort)(&x1300_a_r),
    0x1312, (ushort)(&x1312_c_r),
    0x1400, (ushort)(&x1400_a_t),
    0x1414, (ushort)(&x1414_c_t),
    0x1500, (ushort)(&x1500_a_y),
    0x1519, (ushort)(&x1519_c_y),
    0x1600, (ushort)(&x1600_a_u),
    0x1615, (ushort)(&x1615_c_u),
    0x1700, (ushort)(&x1700_a_i),
    0x1709, (ushort)(&x1709_c_i),
    0x1800, (ushort)(&x1800_a_o),
    0x180f, (ushort)(&x180f_c_o),
    0x1900, (ushort)(&x1900_a_p),
    0x1910, (ushort)(&x1910_c_p),
    0x1c0a, (ushort)(&x1c0a_c_enter),
    0x1c0d, (ushort)(&x1c0d_enter),
    0x1e00, (ushort)(&x1e00_a_a),
    0x1e00, (ushort)(&x1e00_c_a),
    0x1f00, (ushort)(&x1f00_a_s),
    0x1f13, (ushort)(&x1f13_c_s),
    0x2000, (ushort)(&x2000_a_d),
    0x2004, (ushort)(&x2004_c_d),
    0x2100, (ushort)(&x2100_a_f),
    0x2106, (ushort)(&x2106_c_f),
    0x2200, (ushort)(&x2200_a_g),
    0x2207, (ushort)(&x2207_c_g),
    0x2300, (ushort)(&x2300_a_h),
    0x2308, (ushort)(&x2308_c_h),
    0x2400, (ushort)(&x2400_a_j),
    0x240a, (ushort)(&x240a_c_j),
    0x2500, (ushort)(&x2500_a_k),
    0x250b, (ushort)(&x250b_c_k),
    0x2600, (ushort)(&x2600_a_l),
    0x260c, (ushort)(&x260c_c_l),
    0x2900, (ushort)(&x2900_a_tilda),
    0x2b00, (ushort)(&x2b00_a_backslash),
    0x2b1c, (ushort)(&x2b1c_c_backslash),
    0x2c00, (ushort)(&x2c00_a_z),
    0x2c1a, (ushort)(&x2c1a_c_z),
    0x2d00, (ushort)(&x2d00_a_x),
    0x2d18, (ushort)(&x2d18_c_x),
    0x2e00, (ushort)(&x2e00_a_c),
    0x2e03, (ushort)(&x2e03_c_c),
    0x2f00, (ushort)(&x2f00_a_v),
    0x2f16, (ushort)(&x2f16_c_v),
    0x3000, (ushort)(&x3000_a_b),
    0x3002, (ushort)(&x3002_c_b),
    0x3100, (ushort)(&x3100_a_n),
    0x310e, (ushort)(&x310e_c_n),
    0x3200, (ushort)(&x3200_a_m),
    0x320d, (ushort)(&x320d_c_m),
    0x3300, (ushort)(&x3300_a_comma),
    0x3400, (ushort)(&x3400_a_period),
    0x3500, (ushort)(&x3500_a_slash),
    0x3b00, (ushort)(&x3b00_f1),
    0x3c00, (ushort)(&x3c00_f2),
    0x3d00, (ushort)(&x3d00_f3),
    0x3e00, (ushort)(&x3e00_f4),
    0x3f00, (ushort)(&x3f00_f5),
    0x4000, (ushort)(&x4000_f6),
    0x4100, (ushort)(&x4100_f7),
    0x4200, (ushort)(&x4200_f8),
    0x4300, (ushort)(&x4300_f9),
    0x4400, (ushort)(&x4400_f10),
    0x4700, (ushort)(&x4700_home),
    0x47e0, (ushort)(&x47e0_g_home),
    0x47e0, (ushort)(&x47e0_s_g_home),
    0x4800, (ushort)(&x4800_up),
    0x48e0, (ushort)(&x48e0_g_up),
    0x48e0, (ushort)(&x48e0_s_g_up),
    0x4900, (ushort)(&x4900_pgup),
    0x49e0, (ushort)(&x49e0_g_pgup),
    0x49e0, (ushort)(&x49e0_s_g_pgup),
    0x4b00, (ushort)(&x4b00_left),
    0x4be0, (ushort)(&x4be0_g_left),
    0x4be0, (ushort)(&x4be0_s_g_left),
    0x4c00, (ushort)(&x4c00_center),
    0x4d00, (ushort)(&x4d00_right),
    0x4de0, (ushort)(&x4de0_g_right),
    0x4de0, (ushort)(&x4de0_s_g_right),
    0x4f00, (ushort)(&x4f00_end),
    0x4fe0, (ushort)(&x4fe0_g_end),
    0x4fe0, (ushort)(&x4fe0_s_g_end),
    0x5000, (ushort)(&x5000_down),
    0x50e0, (ushort)(&x50e0_g_down),
    0x50e0, (ushort)(&x50e0_s_g_down),
    0x5100, (ushort)(&x5100_pgdn),
    0x51e0, (ushort)(&x51e0_g_pgdn),
    0x51e0, (ushort)(&x51e0_s_g_pgdn),
    0x5200, (ushort)(&x5200_insert),
    0x52e0, (ushort)(&x52e0_g_insert),
    0x52e0, (ushort)(&x52e0_s_g_insert),
    0x5300, (ushort)(&x5300_delete),
    0x53e0, (ushort)(&x53e0_g_delete),
    0x53e0, (ushort)(&x53e0_s_g_delete),
    0x5400, (ushort)(&x5400_s_f1),
    0x5500, (ushort)(&x5500_s_f2),
    0x5600, (ushort)(&x5600_s_f3),
    0x5700, (ushort)(&x5700_s_f4),
    0x5800, (ushort)(&x5800_s_f5),
    0x5900, (ushort)(&x5900_s_f6),
    0x5a00, (ushort)(&x5a00_s_f7),
    0x5b00, (ushort)(&x5b00_s_f8),
    0x5c00, (ushort)(&x5c00_s_f9),
    0x5d00, (ushort)(&x5d00_s_f10),
    0x5e00, (ushort)(&x5e00_c_f1),
    0x5f00, (ushort)(&x5f00_c_f2),
    0x6000, (ushort)(&x6000_c_f3),
    0x6100, (ushort)(&x6100_c_f4),
    0x6200, (ushort)(&x6200_c_f5),
    0x6300, (ushort)(&x6300_c_f6),
    0x6400, (ushort)(&x6400_c_f7),
    0x6500, (ushort)(&x6500_c_f8),
    0x6600, (ushort)(&x6600_c_f9),
    0x6700, (ushort)(&x6700_c_f10),
    0x6800, (ushort)(&x6800_a_f1),
    0x6900, (ushort)(&x6900_a_f2),
    0x6a00, (ushort)(&x6a00_a_f3),
    0x6b00, (ushort)(&x6b00_a_f4),
    0x6c00, (ushort)(&x6c00_a_f5),
    0x6d00, (ushort)(&x6d00_a_f6),
    0x6e00, (ushort)(&x6e00_a_f7),
    0x6f00, (ushort)(&x6f00_a_f8),
    0x7000, (ushort)(&x7000_a_f9),
    0x7100, (ushort)(&x7100_a_f10),
    0x7300, (ushort)(&x7300_c_left),
    0x73e0, (ushort)(&x73e0_c_g_left),
    0x7400, (ushort)(&x7400_c_right),
    0x74e0, (ushort)(&x74e0_c_g_right),
    0x7500, (ushort)(&x7500_c_end),
    0x75e0, (ushort)(&x75e0_c_g_end),
    0x7600, (ushort)(&x7600_c_pgdn),
    0x76e0, (ushort)(&x76e0_c_g_pgdn),
    0x7700, (ushort)(&x7700_c_home),
    0x77e0, (ushort)(&x77e0_c_g_home),
    0x7800, (ushort)(&x7800_a_1),
    0x7900, (ushort)(&x7900_a_2),
    0x7a00, (ushort)(&x7a00_a_3),
    0x7b00, (ushort)(&x7b00_a_4),
    0x7c00, (ushort)(&x7c00_a_5),
    0x7d00, (ushort)(&x7d00_a_6),
    0x7e00, (ushort)(&x7e00_a_7),
    0x7f00, (ushort)(&x7f00_a_8),
    0x8000, (ushort)(&x8000_a_9),
    0x8100, (ushort)(&x8100_a_0),
    0x8200, (ushort)(&x8200_a_hyphen),
    0x8300, (ushort)(&x8300_a_equal),
    0x8400, (ushort)(&x8400_c_pgup),
    0x84e0, (ushort)(&x84e0_c_g_pgup),
    0x8500, (ushort)(&x8500_f11),
    0x8600, (ushort)(&x8600_f12),
    0x8700, (ushort)(&x8700_s_f11),
    0x8800, (ushort)(&x8800_s_f12),
    0x8900, (ushort)(&x8900_c_f11),
    0x8a00, (ushort)(&x8a00_c_f12),
    0x8b00, (ushort)(&x8b00_a_f11),
    0x8c00, (ushort)(&x8c00_a_f12),
    0x8d00, (ushort)(&x8d00_c_up),
    0x8de0, (ushort)(&x8de0_c_g_up),
    0x8f00, (ushort)(&x8f00_c_center),
    0x9100, (ushort)(&x9100_c_down),
    0x91e0, (ushort)(&x91e0_c_g_down),
    0x9200, (ushort)(&x9200_c_insert),
    0x92e0, (ushort)(&x92e0_c_g_insert),
    0x9300, (ushort)(&x9300_c_delete),
    0x93e0, (ushort)(&x93e0_c_g_delete),
    0x9400, (ushort)(&x9400_c_tab),
    0x9700, (ushort)(&x9700_a_g_home),
    0x9800, (ushort)(&x9800_a_g_up),
    0x9900, (ushort)(&x9900_a_g_pgup),
    0x9b00, (ushort)(&x9b00_a_g_left),
    0x9d00, (ushort)(&x9d00_a_g_right),
    0x9f00, (ushort)(&x9f00_a_g_end),
    0xa000, (ushort)(&xa000_a_g_down),
    0xa100, (ushort)(&xa100_a_g_pgdn),
    0xa200, (ushort)(&xa200_a_g_insert),
    0xa300, (ushort)(&xa300_a_g_delete),
    0xa500, (ushort)(&xa500_a_tab),
    0xa600, (ushort)(&xa600_a_g_enter),
    0xe00a, (ushort)(&xe00a_c_g_enter),
    0xe00d, (ushort)(&xe00d_g_enter),
    0xe00d, (ushort)(&xe00d_s_g_enter),
    0xffff, (ushort)(&press_a_key)
};