@echo off
PATH=c:\c600\bin;c:\c600\binp;c:\sem32\;C:\WINDOWS\SYSTEM32;C:\WINDOWS;C:\WINDOWS\SYSTEM32\WBEM;C:\PROGRA~1\ESTSOFT\ALZIP\;C:\PROGRA~1\Q
SET INCLUDE=c:\c600\include\;
SET LIB=c:\c600\lib;
